version: "3.8"

services:
  trustless_node:
    image: ghcr.io/trustlesscomputer/tc:latest
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "trustless_node_public"
    env_file:
      - ./tc.env
    network_mode: "host"
    command: [
      "/app/tc",
      "-r",
      "-a",
      "-m", "${TC_BTC_WALLET_ADDRESS}:${TC_BTC_WALLET_AMOUNT}",
      "-g",
      "-u", "${BITCOIND_RPC_USERNAME}",
      "-p", "${BITCOIND_RPC_PASSWORD}",
      "-e", "${BITCOIND_RPC_ENDPOINT}",
      "--btc-wallet", "${TC_BTC_WALLET_NAME}"
    ]
    volumes:
      - ./trustless_node_data:/app/tcdata
 
  redis_db:
    extends:
      file: ./explorer/services/docker-compose-redis.yml
      service: redis_db

  db:
    extends:
      file: ./explorer/services/docker-compose-db.yml
      service: db

  explorer:
    depends_on:
      - trustless_node
      - db
      - smart-contract-verifier
      - redis_db
    extends:
      file: ./explorer/docker-compose-explorer.yml
      service: blockscout
  smart-contract-verifier:
    extends:
      file: ./explorer/services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./explorer/services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./explorer/services/docker-compose-sig-provider.yml
      service: sig-provider
