version: "3.8"

services:
  trustless_node:
    image: ghcr.io/trustlesscomputer/tc:latest
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "trustless_node_public"
    network_mode: "host"
    command: [
      "/app/tc",
      "-r",
      "-a",
      "--inscribe-mode", "auto",
      "-m", "0xB8Bc42098CC278e03302DbcF9138Cf04b22e6c04:52b7d2dcc80cd2e4000000",
      "-u", "trustless",
      "-p", "notrespassing",
      "-e", "127.0.0.1:8332",
      "--btc-wallet", "trustless"
    ]
    volumes:
      - ./trustless_node_data:/app/tcdata
 
  redis_db:
    extends:
      file: ./explorer/services/docker-compose-redis.yml
      service: redis_db

  db:
    extends:
      file: ./explorer/services/docker-compose-db.yml
      service: db

  explorer:
    depends_on:
      - trustless_node
      - db
      - smart-contract-verifier
      - redis_db
    extends:
      file: ./explorer/docker-compose-explorer.yml
      service: blockscout
  smart-contract-verifier:
    extends:
      file: ./explorer/services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./explorer/services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./explorer/services/docker-compose-sig-provider.yml
      service: sig-provider
