version: '3.8'

services:
  sig-provider:
    platform: linux/x86_64
    image: ghcr.io/blockscout/sig-provider:main
    pull_policy: always
    restart: always
    container_name: 'sig-provider'
    ports:
      - 8151:8050
