version: "3.8"

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  blockscout:
    platform: linux/x86_64
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    image: synxless/blockscout:latest
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "blockscout"
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: https://tc-node-auto.regtest.trustless.computer
      ETHEREUM_JSONRPC_TRACE_URL: https://tc-node-auto.regtest.trustless.computer
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: "false"
      SECRET_KEY_BASE: "56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"
      COIN: "TC"
      COIN_NAME: "TC"
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: "true" # disable block reward indexer as Polygon Edge doesn't support tracing
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true" # disable pending transactions indexer as Polygon Edge doesn't support tracing
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true" # disable internal transactions indexer as Polygon Edge doesn't support tracing
      MIX_ENV: "prod" # run in production mode
      BLOCKSCOUT_PROTOCOL: "http" # protocol to run blockscout web service on
      PORT: 4000 # port to run blockscout service on
      DISABLE_EXCHANGE_RATES: "true" # disable fetching of exchange rates
      # POOL_SIZE: 50 # the number of database connections
      # POOL_SIZE_API: 50 # the number of read-only database connections
      HEART_BEAT_TIMEOUT: 60 # run HEARTH_COMMAND if heartbeat missing for this amount of seconds
      INDEXER_MEMORY_LIMIT: "5Gb" # soft memory limit for indexer - depending on the size of the chain and the amount of RAM the server has
      FETCH_REWARDS_WAY: "manual" # disable trace_block query
      TOKEN_ID_MIGRATION_BATCH_SIZE: 50
      INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: 50
      INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE: 50
      INDEXER_TOKEN_INSTANCE_BATCH_SIZE: 50
      INDEXER_COIN_BALANCES_BATCH_SIZE: 50
      INDEXER_RECEIPTS_BATCH_SIZE: 50
      INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE: 50 # sanitize empty block in this batch size
      SUBNETWORK: "Trustless Computer"
      DISABLE_TOKEN_INSTANCE_FETCHER: "true"
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider
